### ISSUE TITLE
model doesn't respond to `has_fields?`

### ISSUE THREAD

**Issue by doodzik** [mongoid-rspec/mongoid-rspec#134]
When i comment ```, type: :model``` out it works as expected
```ruby
RSpec.configure do |config|
  config.include Mongoid::Matchers#, type: :model
end
```

my setup is something like this:
```ruby
require 'rspec'
require_relative '../loadpath'
require 'environment'

require 'mongoid'
require 'mongoid-rspec'

RSpec.configure do |config|
  config.include Mongoid::Matchers#, type: :model
end

class User
    include Mongoid::Document
    field :name
    field :email
end

describe User do
 it { should have_fields(:email, :name) }
end
```

```ruby
gem 'mongoid', "~> 4.0.0"
gem 'mongoid-rspec', '~> 2.0.0.rc1'
```

**Comment by rodrigopinto** [comment]
@doodzik I released the `2.0.0` and even it's passing on our test suite. Could you confirm that everything is ok?

**Comment by doodzik** [comment]
I've updated  mongoid-rspec and the problem still occurs :(

all the specs fail with undefined method $matcher

example:
```
     Failure/Error: it { should validate_presence_of(:email) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::ExampleGroups::User:0x007f9edeb2c698>
```

**Comment by rodrigopinto** [comment]
@doodzik Try to configure only with `config.include Mongoid::Matchers` without set the type.

**Comment by doodzik** [comment]
mongoid-rspec's spec_helper doesn't include the ```type: :model``` either
https://github.com/mongoid-rspec/mongoid-rspec/blob/master/spec/spec_helper.rb#L27

why is it important to dispatch ```include``` with``` type: :model``` ?

**Comment by rodrigopinto** [comment]
@doodzik It's the opposite, there is no need to set the type on rspec configuration. As you saw we don't have any configuration on our test suite.

It's only needed if you are using a different directory structure. Like [described here](https://relishapp.com/rspec/rspec-rails/docs/directory-structure).

**Comment by doodzik** [comment]
I'm going to close this issue. It had to do with me not getting that ```type: :model``` is added for the rails directory structure.

@rodrigopinto It would be nice if we could add something to the readme to avoid someone else the confusion.

Thank your for your help and time. I appreciate it.

**Comment by rodrigopinto** [comment]
@doodzik You are welcome! I'll take some time to update the README, but if you would like to send me a PR with this information would be nice too.

Thanks! :+1:
